### ISSUE TITLE
🚧Replace moq with nsubstitute

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/PackageMonster#132]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Replace all Moq code with NSubstitute code.

The files below are the only files that have Moq code setup:
1. _**GitHubActionTests.cs**_
2. _**MoqExtensions.cs**_
3. _**ActionOutputServiceTests.cs**_

Install the following NuGet packages in the **_PackageMonsterTests_** project
1. NSubstitute version _**v5.1.0**_
2. NSubstitute.Analyzers.CSharp version _**v1.0.16**_

Remove the following NuGet packages from the **_PackageMonsterTests_** project
1. Moq

### Acceptance Criteria

- [ ] NSubstitute packages installed
- [ ] Moq package removed
- [ ] Moq code replaced with NSubstitute code
    - [ ] Code replaced in the _**GitHubActionTests.cs**_ file
    - [ ] Code replaced in the _**MoqExtensions.cs**_ file
    - [ ] Code replaced in the _**ActionOutputServiceTests.cs**_ file

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
