### ISSUE TITLE
🚧Fix issues with readme

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/PackageMonster#78]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix various issues with the project's readme file.

1. Fix the logo.  The URL to the raw GitHub content is incorrect.
2. Fix the MIT link in the **Licensing And Governance** paragraph at the bottom by not making a link
3. Fix the license badge by linking it to the project MIT license

### Acceptance Criteria

```[tasklist]
- [ ] Logo URL fixed
- [ ] MIT URL link in the paragraph is removed and text left behind
- [ ] The MIT license badge goes to the project's license when clicked.
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
