### ISSUE TITLE
🚧Update release note templates

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/PackageMonster#83]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the titles in the release note template files.

Currently, the title still shows GotNuget.  This needs to be updated to _**Package Monster**_.

> **Note** The title release notes for version _**v1.0.0-preview.1**_ also needs to be updated

**Example:**
```diff
<h1 align="center" style='color:mediumseagreen;font-weight:bold'>
-    GotNuget Production Release Notes - [add-prod-release-here]
+    GotNuget Production Release Notes - [add-prod-release-here]
</h1>
```

### Acceptance Criteria

- [ ] Title in preview release note template file updated
- [ ] Title in production release note template file updated
- [ ] Title in `v1.0.0-preview.1` preview release notes updated

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
