### ISSUE TITLE
🚧Create status checks

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/PackageMonster#86]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a new status check that will execute for PRs that merge from a feature branch to a master branch.

**Things to implement:**
1. The name of the status check file will be _**version-notes-status-check.yml**_.
2. First check will check if a tag exists with the same name as the current version in the csproj file.  If it does, it will fail.
3. If the first check (step) passes, it will then check if the release notes for that version already exist, and if not, it will fail.
4. The status check should only run when changes are made for _**.cs**_ and _**.csproj**_ files.
5. Set up the triggers for the paths mentioned in step 4 as well as for the master branch. Refer to the setup below:
```yml
on:
  pull_request:
    branches:
      - master
    paths:
      - "**.cs"
      - "**.csproj"
```

### Acceptance Criteria

- [x] Status check workflow created
    - [x] Checks if the version in the csproj already exists as a tag
    - [x] The workflow named as _**version-notes-status-check.yml**_
    - [x] The workflow must only run when changes are made for _**.cs**_ and _**.csproj**_ files
    - [x] Triggers setup for pull requests merging into master.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
