### ISSUE TITLE
🚧Update workflow to use org level scripts

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/PackageMonster#89]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the _**version-notes-status-check.yml**_ workflow to use the organization-level validation scripts instead of the local scripts.  After the workflow has been updated, delete the local scripts due to them not being needed anymore.  

They are not needed anymore because they have been moved to the organization-level _**Infrastructure**_ repository.
The steps _**Validate Tag**_ and _**Validate Release Notes**_ are the steps that need updating.  The _**deno**_ command for these steps are using file paths that point to the local scripts.  These need to be updated to URLs instead.  The URL will be the raw GitHub user content of the scripts that lives in the _**Infrastructure**_ repository

> **Note** Why raw GitHub user URL?
> This is because raw GitHub URLs return the original raw content of a file from a repo instead of a web page.  This means the script would literally be returned as the string file content of the scripts which is what _**deno**_ needs.  The only thing that we need to make sure of is that we are using a certain _**version**_ of the script, so the URL needs to be a URL to the script file for a particular version tag.  This will give us the ability to version the scripts for easy upgrades across the organization.

**Example Raw URL For Tag:**
https://raw.githubusercontent.com/KinsonDigital/Infrastructure/v3.0.3/cicd/validate-tag.ts

### Acceptance Criteria

- [x] The _**version-notes-status-check.yml**_ workflow updated to use the org level scripts
- [x] The _**release.yml**_ workflow updated to use the org level scripts
  > **Note** These are located in the **Validate Tag** and **Validate Release Notes** steps
- [x] Local scripts deleted
    - [x] _**validate-tag.ts**_ script deleted
    - [x] _**validate-notes.ts**_ script deleted
    - [x] _**cicd/**_ folder deleted

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
