### ISSUE TITLE
🚧Improve release workflow 

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/PackageMonster#95]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Improve the release workflow by having it point to the reusable release workflow for dotnet GitHub actions, adding sync capability and a new "add new workflow."

These reusable workflow exists in the Infrastructure repository with the name _**dotnet-action-release.yml**_., add-newissue-to-project.yml and all yml files starting with sync. 

> **Note** There is a dependency on the reusable workflow being created first.  This should be shown below.

### Acceptance Criteria

- [x] Release workflow changed to use the reusable workflow below
- [x] The workflow will be setup to do preview OR production releases
- [x] All sync .yml are created
- [x] Add new issue to project .yml created

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if applicable)_.
- [X] Issue linked to the correct milestone _(if applicable)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Issue Dependencies

- KinsonDigital/Infrastructure#80

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
